parameters:
  - name: buildFile
    default: build.xml
  - name: options       # Optional
    default: ' '
  - name: targets         # Optional
    default: ' '
  - name: antHomeDirectory  # Optional
    default: ' '
  - name: jdkDirectory
    default: ' '
  - name: javaHomeOption
    default: 'JDKVersion'
  - name: jdkVersionOption
    default: 'default'
  - name: jdkUserInputDirectory  # Required when javaHomeOption == Path
    default: ' '
  - name: publishJUnitResults
    default: true
  - name: testResultsFiles  # Required when publishJUnitResults == True
    default: '**/TEST-*.xml'

stages:
- stage: Build
  jobs:
  - job: AntBuild
    steps:
    - task: Ant@1
      inputs:
       buildFile: ${{ parameters.buildFile }}
       javaHomeOption: ${{ parameters.javaHomeOption }}                  # Options: jDKVersion, path
       jdkVersionOption: ${{ parameters.jdkVersionOption }}              # Optional. Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6
       options: ${{ parameters.options }}                                # Optional
       targets: ${{ parameters.targets }}                                # Optional
       antHomeDirectory: ${{ parameters.antHomeDirectory }}              # Optional
       jdkDirectory: ${{ parameters.jdkDirectory }}
       jdkUserInputDirectory: ${{ parameters.jdkUserInputDirectory }}    # Required when javaHomeOption == Path
       publishJUnitResults: ${{ parameters.publishJUnitResults }}
       testResultsFiles: ${{ parameters.testResultsFiles }}              # Required when publishJUnitResults == True


