parameters:
  - name: buildFile        #(Required) Relative path from the repository root to the Ant build file
    default: build.xml
  - name: options          #(Optional) Options that you want to pass to the Ant command line
    default: ' '
  - name: targets          #(Optional) Target(s) for Ant to execute for this build.
    default: ' '
  - name: antHomeDirectory #(Optional) If set, overrides any existing ANT_HOME environment variable with the given path.
    default: ' '
  - name: javaHomeOption   #(Required) Sets JAVA_HOME either by selecting a JDK version that will be discovered during builds or 
    default: 'JDKVersion'  #by manually entering a JDK path. 
  - name: jdkVersionOption #(Optional) Will attempt to discover the path to the selected JDK version and set JAVA_HOME accordingly. 
    default: 'default'     
  - name: jdkUserInputDirectory  #(Required) when javaHomeOption == Path Sets JAVA_HOME_PATH to the given path 
    default: ' '
  - name: publishJUnitResults  #(optional) Select this option to publish JUnit test results 
    default: true
  - name: testResultsFiles  # Required when publishJUnitResults == True
    default: '**/TEST-*.xml'

stages:
- stage: Build
  jobs:
  - job: AntBuild
    steps:
    - task: Ant@1
      inputs:
       buildFile: ${{ parameters.buildFile }}
       javaHomeOption: ${{ parameters.javaHomeOption }}                  
       jdkVersionOption: ${{ parameters.jdkVersionOption }}              
       options: ${{ parameters.options }}                                
       targets: ${{ parameters.targets }}                                
       antHomeDirectory: ${{ parameters.antHomeDirectory }}              
       jdkDirectory: ${{ parameters.jdkDirectory }}
       jdkUserInputDirectory: ${{ parameters.jdkUserInputDirectory }}    
       publishJUnitResults: ${{ parameters.publishJUnitResults }}
       testResultsFiles: ${{ parameters.testResultsFiles }}              


