parameters:
  - name: artifactoryService  #(Required) Service connection name used to communicate with Jfrog artifactory
    default: 'Artifactory'   
  - name: specSource          #(Required) Path of build artifacts to be published to jfrog artifactory
    default: 'taskConfiguration'
  - name: Artifactory_variable_Group #(Required) Contains variables related to Jforg artifactory in variable group
    default: 'Artifactory_Variables'
  - name: Artifact_Version #(Required) This will take build number by default, if requires any modification other than 
    default: ''            #build number we need to pass the value
  - name: failNoOp   #(Required) This will fail the piupeline execution if no files uploaded to Jfrog artifactory
    default: true
stages:
- stage: Artifactory_Download
  jobs:
  - job: Build_Artifact_Download
    variables:
    - group: ${{ parameters.Artifactory_variable_Group }}
    steps:
     - task: ArtifactoryGenericDownload@2                 
       displayName: 'Download scanned artifacts from Jfrog'
       inputs:
        connection: ${{ parameters.artifactoryService }}
        specSource: ${{ parameters.specSource }}
        ${{ if eq(parameters['specSource'], 'taskConfiguration') }}:    # To upload artifacts of same type in a folder or entire folder.
          fileSpec: |
           {
            "files": [
              {
                "pattern": "$(Download_src_lctn)/${{ parameters.Artifact_version }}/*",
                "target": "$(Download_dest_lctn)"           
              }
            ]
           }
        ${{ if ne(parameters['specSource'], 'taskConfiguration') }}:     #To upload multiple artifacts from various folders.
          file: $(File_lctn)
        failNoOp: ${{ parameters.failNoOp }}
     - publish: "$(System.DefaultWorkingDirectory)/$(Scanned_artifact_lctn)/${{ parameters.Artifact_version }}"
       artifact: $(Scanned_Artifact_Name)
