parameters:
  - name: artifactoryService
    default: 'Artifactory'
  - name: specSource
    default: 'taskConfiguration'
  - name: Artifactory_variable_Group
    default: 'Artifactory_Variables'
  - name: Artifact_Version
    default: ''
  - name: failNoOp
    default: true
stages:
- stage: Artifactory_Download
  jobs:
  - job: Build_Artifact_Download
    variables:
    - group: ${{ parameters.Artifactory_variable_Group }}
    steps:
     - task: ArtifactoryGenericDownload@2
       displayName: 'Download scanned artifacts from Jfrog'
       inputs:
        connection: ${{ parameters.artifactoryService }}
        specSource: ${{ parameters.specSource }}
        ${{ if eq(parameters['specSource'], 'taskConfiguration') }}:
          fileSpec: |
           {
            "files": [
              {
                "pattern": "$(Download_src_lctn)/${{ parameters.Artifact_version }}/*",
                "target": "$(Download_dest_lctn)"
              }
            ]
           }
        ${{ if ne(parameters['specSource'], 'taskConfiguration') }}:
          file: $(File_lctn)
        failNoOp: ${{ parameters.failNoOp }}
     - publish: "$(System.DefaultWorkingDirectory)/$(Scanned_artifact_lctn)/${{ parameters.Artifact_version }}"
       artifact: $(Scanned_Artifact_Name)
