parameters:
  - name: sshEndpoint
    default: 'SSH'
  - name: runOptions
    default: 'commands'
  - name: commands
    default: ' '
  - name: scriptPath
    default: ' ' 
  - name: inline
    default: ' '
  - name: failOnStdErr
    default: true
stages:
- stage: Deployment_Dev
  jobs:
  - deployment: dev_deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, dev world !!!"
          - script: ls -la

- stage: Deployment_QA
  jobs:
  - deployment: qa_deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'qa'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, qa world !!!"
- stage: Deployment_PROD
  jobs:
  - deployment: qa_prod
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'PROD'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, prod world !!!"
