parameters:
  - name: sshEndpoint
    default: 'SSH'
  - name: sourceFolder
    default: '$(Pipeline.Workspace)/ScannedArtifacts/'
  - name: contents
    default: '*.war'
  - name: targetFolder
    default: '/opt/demo/' 
  - name: cleanTargetFolder   # Optional
    default: false
  - name: overwrite           # Optional
    default: true
  - name: failOnEmptySource      # Optional 
    default: true
  - name: flattenFolders        # Optional
    default: true
 # Copy files over SSH
  # Copy files or build artifacts to a remote machine over SSH   
 
stages:
- stage: CopyArtifacts
  jobs:
  - job: CopyArtifacts
    steps:
    - download: current
      artifact: ScannedArtifacts
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: ${{ parameters.sshEndpoint }}
        sourceFolder: ${{ parameters.sourceFolder }}
        contents: ${{ parameters.contents }}
        targetFolder: ${{ parameters.targetFolder }}
        cleanTargetFolder: ${{ parameters.cleanTargetFolder }}        # Optional
        overwrite: ${{ parameters.overwrite }}                         # Optional
        failOnEmptySource: ${{ parameters.failOnEmptySource }}        # Optional
        flattenFolders: ${{ parameters.flattenFolders }}         # Optional
