parameters:
  - name: sshEndpoint
    default: 'SSH'
  - name: runOptions
    default: 'commands'
  - name: commands
    default: ' '
  - name: scriptPath
    default: ' ' 
  - name: inline
    default: ' '
  - name: failOnStdErr
    default: true
stages:
- stage: Deployment
  jobs:
  - job: Deployment_Dev
    steps:
      - task: SSH@0
        displayName: 'Run shell commands on remote machine'
        inputs:
          sshEndpoint: ${{ parameters.sshEndpoint }}
          runOptions: ${{ parameters.runOptions }}
          commands: ${{ parameters.commands }}
          scriptPath: ${{ parameters.scriptPath }}
          inline: ${{ parameters.inline }}
          args: ${{ parameters.args }}
          failOnStdErr: ${{ parameters.failOnStdErr }}  # Optional
