parameters:
  - name: sshEndpoint
    default: 'SSH'
  - name: runOptions
    default: 'commands'
  - name: commands
    default: ' '
  - name: scriptPath
    default: ' ' 
  - name: inline
    default: ' '
  - name: failOnStdErr
    default: true
stages:
- stage: ${{ parameters.stage }}
  jobs:
  - deployment: ${{ parameters.job }}
    pool: 
      vmImage: 'Ubuntu-16.04'
    environment: ${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, dev world !!!"
          - script: ls -la

