parameters:
  - name: mavenPomFile
    default: pom.xml
  - name: options
    default: ' '
  - name: goals
    default: package
  - name: jdkDirectory
    default: ' '
  - name: javaHomeOption
    default: 'JDKVersion'
  - name: jdkVersionOption
    default: 'default'
  - name: mavenDirectory
    default: ' '
  - name: mavenVersionOption
    default: 'default'
  - name: mavenSetM2Home
    default: false
  - name: publishJUnitResults
    default: true
  - name: testResultsFiles
    default: '**/surefire-reports/TEST-*.xml'
stages:
- stage: Build
  jobs:
  - job: MavenBuild
    variables:
    - group: Artifactory_Variables
    steps:
    - task: Maven@3
      displayName: 'Maven Build'
      inputs:
        goals: ${{ parameters.goals }}
        mavenPomFile: ${{ parameters.mavenPomFile }}
        javaHomeOption: ${{ parameters.javaHomeOption }}
        jdkVersionOption: ${{ parameters.jdkVersionOption }}
        jdkDirectory: ${{ parameters.jdkDirectory }}
        mavenDirectory: ${{ parameters.mavenDirectory }}
        mavenVersionOption: ${{ parameters.mavenVersionOption }}
        mavenSetM2Home: ${{ parameters.mavenSetM2Home }}
        options: ${{ parameters.options }}
        publishJUnitResults: ${{ parameters.publishJUnitResults }}
        testResultsFiles: ${{ parameters.testResultsFiles }}
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
       Contents: "$(build_artifact_Path)"
       TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: $(PlneArtifact_Name)'
      inputs:
       ArtifactName: $(PlneArtifact_Name)